### ISSUE TITLE
Crashes on startup on Windows 10 Creators Update

### ISSUE THREAD

**Issue by Bobens** [CodeSwine/GTA5Online-Private_Public_Lobby#3]
Latest update has forced net Framework 4.7.1 which might be a problem here. It cannot be downgraded though.
Tried to find any similar problem in comments, but it feels like I am the only one.
Also, https://github.com/Microsoft/dotnet/blob/master/releases/net471/KnownIssues/510901-BCL%20Apps%20targeting%20.NET-4.6.1%20that%20use%20.NET%20Standard%20libraries%20might%20be%20broken%20when%20running%20on%20.NET%204.7.1.md

**Comment by CodeSwine** [comment]
Hi thanks for bringing up this issue, I'll look into it soon. Might have some free time in a few days.

**Comment by CodeSwine** [comment]
Sorry for my absence I don't really have time to work on this anymore. I updated to .NET Framework 4.7.1 and verified using the following powershell command: `Get-ChildItem "HKLM:SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\"
| Get-ItemPropertyValue -Name Release | ForEach-Object { $_ -ge 461308 }` and the tool still works for me. 

I'll attach a .NET 4.7.1 build, for future references, please make sure `Newtonsoft.Json.dll` is in the same folder as the executable otherwise it'll crash without any message.

[CodeSwine.GTA5O.-.Private.Public.Lobby.V1.0.1.-.NET4.7.1.zip](https://github.com/CodeSwine/GTA5Online-Private_Public_Lobby/files/1792488/CodeSwine.GTA5O.-.Private.Public.Lobby.V1.0.1.-.NET4.7.1.zip)
